# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: license-check.txt|^(docs/|notebooks/|data/|src/secrets/|src/static/|src/templates/test)
default_language_version:
    python: python3.8
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: check-added-large-files
    - id: check-ast
    - id: check-builtin-literals
    - id: check-case-conflict
    - id: check-docstring-first
    - id: check-shebang-scripts-are-executable
    - id: check-json
    - id: check-merge-conflict
    - id: check-toml
    - id: check-vcs-permalinks
    - id: debug-statements
    - id: destroyed-symlinks
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: mixed-line-ending
    #- id: name-tests-test #TODO: need to figure out why this doesn't run
    - id: trailing-whitespace
    #- id: check-byte-order-marker
    #- id: check-symlinks
    #- id: check-xml
    #- id: check-yaml
    #- id: check-executables-have-shebangs
    #- id: pretty-format-json

  - repo: https://github.com/PyCQA/isort
    rev: '5.11.4'
    hooks:
    - id: isort
      args: ["--profile", "black", "."]
  - repo: https://github.com/psf/black
    rev: '22.12.0'
    hooks:
    - id: black
      args: [--line-length=120]
  # - repo: https://github.com/FHPythonUtils/LicenseCheck
  #   rev: '2023'
  #   hooks:
  #   - id: licensecheck
  #     args: ["--file", "/tmp/license-check.txt",
  #            "--ignore-packages", "pymupdf", "&&", "git", "diff",
  #            "/tmp/license-check.txt", "license-check.txt"]
