[prehooks]


[posthooks]

[themes]
  catpuccin_latte =     "../themes/catpuccin-latte.toml"
  catpuccil_frappe =    "..themes/catpuccin-frappe.toml"
  catpuccin_macchiato = "..themes/catpuccin-macchiato"
  catpuccin_mocha =     "../themes/catpuccin-mocha.toml"
  darcula =             "../themes/darcula.toml"
  gruvbox =             "../themes/gruvbox.toml"
  dynaconf_docs_dark =  "../themes/dynaconf-docs-dark.toml"
  julia_docs_dark =     "../themes/dynaconf-docs-dark.toml"
  nushell_docs_dark =   "../themes/dynaconf-docs-dark.toml"
  poetry_docs_dark =    "../themes/dynaconf-docs-dark.toml"
  schwarzwald =         "../themes/dynaconf-docs-dark.toml"
  solarized_dark =      "../themes/solarized-dark.toml"
  solarized_light =     "../themes/solarized-light.toml"

[apps]

  [apps.neovim]
  config_file = "@format {env[XDG_CONFIG_HOME]/nvim/..."
  pluginfile = "..."

  [apps.zathura]
  config_file = "@format {env[XDG_CONFIG_HOME]/zathura/..."

  [apps.vifm]
  config_file= "@format {env[XDG_CONFIG_HOME]/vifm/..."

  [apps.qutebrowser]
  config_file = "@format {env[XDG_CONFIG_HOME]/qutebrowser/..."

  [apps.alacritty]
  config_file = "@format {env[XDG_CONFIG_HOME]/alacritty/alacritty.yaml"

  [apps.gnome]


  [apps.xmonad]


  [apps.xmobar]


  [apps.picom]


  [apps.taskell]
  [apps.taskwarrior]


  [chromefox.youtube_enhancer]


  [chromefox.stylish]


    [firechrome.stylish.wikipedia]


    [firechrome.stylish.github]


    [firechrome.stylish.teams]
